[project]
name = "autoimmune-disorder-prediction"
version = "0.1.0"
description = "Autoimmune Disorder Prediction model."
readme = "README.md"
authors = [
    { name = "Emiliano Gandini Outeda", email = "emiliano.gandini@protonmail.com" }
]
requires-python = ">=3.12.7"
dependencies = [
    "kagglehub>=1.0.2",
    "pandas>=3.0.5",
]

[project.scripts]
predict = "autoimmune_disorder_prediction:main"
download = "autoimmune_disorder_prediction.download_data:download"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
